[package]
name = "simple_server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
futures-util = {workspace = true}
log = {workspace = true}
env_logger = {workspace = true}